name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify your Node version

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run
